import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  FileQuestion,
  Package,
  PackageCheck,
  Send,
  ShieldCheck,
  Truck,
  WalletCards,
} from "lucide-react";
import type { Order, OrderPriority, OrderSource, OrderStatus, StatusConfig } from "@/src/types/order";

export const sourceLabels: Record<OrderSource, string> = {
  "woocommerce-weltflagge": "weltflagge.de",
  "woocommerce-partner": "Woo shop 2",
  ebay: "eBay",
  email: "E-Mail",
};

export const priorityLabels: Record<OrderPriority, string> = {
  normal: "Normal",
  high: "High",
  urgent: "Urgent",
};

export const statuses: OrderStatus[] = [
  "New",
  "Payment open",
  "Print files missing",
  "Print files review",
  "Customer reply needed",
  "Approval missing",
  "Production ready",
  "In production",
  "Ready to ship",
  "Shipped",
  "Completed",
];

export const statusConfig: Record<OrderStatus, StatusConfig> = {
  New: {
    icon: ShieldCheck,
    chip: "border-slate-700 bg-slate-900 text-slate-200",
    accent: "from-slate-500 to-slate-400",
  },
  "Payment open": {
    icon: WalletCards,
    chip: "border-red-500/25 bg-red-500/10 text-red-200",
    accent: "from-red-400 to-red-300",
  },
  "Print files missing": {
    icon: FileQuestion,
    chip: "border-amber-500/25 bg-amber-500/10 text-amber-200",
    accent: "from-amber-400 to-amber-300",
  },
  "Print files review": {
    icon: AlertTriangle,
    chip: "border-slate-700 bg-slate-900 text-slate-200",
    accent: "from-slate-500 to-slate-400",
  },
  "Customer reply needed": {
    icon: Send,
    chip: "border-red-500/25 bg-red-500/10 text-red-200",
    accent: "from-red-400 to-red-300",
  },
  "Approval missing": {
    icon: Clock,
    chip: "border-amber-500/25 bg-amber-500/10 text-amber-200",
    accent: "from-amber-400 to-amber-300",
  },
  "Production ready": {
    icon: PackageCheck,
    chip: "border-emerald-500/25 bg-emerald-500/10 text-emerald-200",
    accent: "from-emerald-400 to-emerald-300",
  },
  "In production": {
    icon: Package,
    chip: "border-cyan-500/25 bg-cyan-500/10 text-cyan-200",
    accent: "from-cyan-400 to-cyan-300",
  },
  "Ready to ship": {
    icon: CheckCircle2,
    chip: "border-emerald-500/25 bg-emerald-500/10 text-emerald-200",
    accent: "from-emerald-400 to-emerald-300",
  },
  Shipped: {
    icon: Truck,
    chip: "border-slate-700 bg-slate-900 text-slate-300",
    accent: "from-slate-300 to-slate-500",
  },
  Completed: {
    icon: CheckCircle2,
    chip: "border-slate-700 bg-slate-950 text-slate-400",
    accent: "from-slate-400 to-slate-600",
  },
};

export const mockOrders: Order[] = [
  {
    id: "WF-10482",
    source: "woocommerce-weltflagge",
    externalId: "wc-58241",
    date: "2026-05-15",
    customer: "Stadtverwaltung Musterstadt",
    email: "einkauf@musterstadt.de",
    phone: "+49 30 123456",
    billingAddress: {
      company: "Stadtverwaltung Musterstadt",
      name: "Anna Keller",
      street: "Rathausplatz 1",
      postalCode: "10115",
      city: "Berlin",
      country: "Germany",
    },
    shippingAddress: {
      company: "Stadtverwaltung Musterstadt",
      name: "Wareneingang",
      street: "Rathausplatz 1",
      postalCode: "10115",
      city: "Berlin",
      country: "Germany",
    },
    items: [
      {
        name: "Hissfahne",
        sku: "HF-120-300",
        size: "120 x 300 cm",
        quantity: 2,
        printFile: { status: "received", fileName: "WF-10482_hissfahne_preview.pdf" },
        production: { manufacturer: "opinion", status: "draft" },
      },
    ],
    amount: "178,40 EUR",
    paymentStatus: "Paid",
    artworkStatus: "Druckfreigabe fehlt",
    status: "Approval missing",
    carrier: "-",
    trackingNumber: "",
    priority: "normal",
    deadline: "2026-05-20",
    notes: "Customer should approve the print preview before production starts.",
    timeline: [
      { id: "WF-10482-1", timestamp: "2026-05-15 09:42", actor: "WooCommerce", message: "Order imported from weltflagge.de." },
      { id: "WF-10482-2", timestamp: "2026-05-15 10:05", actor: "System", message: "Payment marked as paid." },
      { id: "WF-10482-3", timestamp: "2026-05-15 10:18", actor: "Prepress", message: "Print preview created. Waiting for Druckfreigabe." },
    ],
  },
  {
    id: "WF-10481",
    source: "woocommerce-partner",
    externalId: "wc2-19204",
    date: "2026-05-15",
    customer: "BakerBuildings UG",
    email: "office@bakerbuildings.de",
    phone: "+49 40 882211",
    billingAddress: {
      company: "BakerBuildings UG",
      name: "Jonas Weber",
      street: "Industriestrasse 24",
      postalCode: "20095",
      city: "Hamburg",
      country: "Germany",
    },
    shippingAddress: {
      company: "BakerBuildings UG",
      name: "Marketing",
      street: "Industriestrasse 24",
      postalCode: "20095",
      city: "Hamburg",
      country: "Germany",
    },
    items: [
      {
        name: "PVC Banner",
        sku: "BN-500-100",
        size: "500 x 100 cm",
        quantity: 1,
        printFile: { status: "approved", fileName: "WF-10481_banner_500x100.pdf" },
        production: { manufacturer: "opinion", batchId: "batch-2026-05-16-opinion", status: "sent" },
      },
    ],
    amount: "92,70 EUR",
    paymentStatus: "Paid",
    artworkStatus: "Druckdaten geprueft",
    status: "In production",
    carrier: "DPD",
    trackingNumber: "",
    priority: "high",
    deadline: "2026-05-18",
    notes: "Logo file is clean. Production can continue.",
    timeline: [
      { id: "WF-10481-1", timestamp: "2026-05-15 08:55", actor: "Woo shop 2", message: "Order imported from secondary WooCommerce shop." },
      { id: "WF-10481-2", timestamp: "2026-05-15 09:11", actor: "Prepress", message: "PDF checked and approved for print." },
      { id: "WF-10481-3", timestamp: "2026-05-15 11:30", actor: "Production", message: "Moved to production queue." },
    ],
  },
  {
    id: "WF-10480",
    source: "email",
    externalId: "mail-9281",
    date: "2026-05-14",
    customer: "Feuerwehr Beispiel e.V.",
    email: "kontakt@feuerwehr-beispiel.de",
    phone: "+49 89 555019",
    billingAddress: {
      company: "Feuerwehr Beispiel e.V.",
      name: "Markus Brandt",
      street: "Hauptstrasse 7",
      postalCode: "80331",
      city: "Muenchen",
      country: "Germany",
    },
    shippingAddress: {
      company: "Feuerwehr Beispiel e.V.",
      name: "Geraetewart",
      street: "Feuerwehrweg 2",
      postalCode: "80331",
      city: "Muenchen",
      country: "Germany",
    },
    items: [
      {
        name: "Beachflag inkl. Gestaltungsservice",
        sku: "BF-M-DESIGN",
        size: "M",
        quantity: 1,
        printFile: { status: "missing", fileName: "" },
        production: { manufacturer: "mph_maciej", status: "not_routed" },
      },
    ],
    amount: "249,95 EUR",
    paymentStatus: "Open",
    artworkStatus: "Design-Service offen",
    status: "Customer reply needed",
    carrier: "-",
    trackingNumber: "",
    priority: "urgent",
    deadline: "2026-05-17",
    notes: "Clarify logo placement and whether the old brand colors are still valid.",
    timeline: [
      { id: "WF-10480-1", timestamp: "2026-05-14 15:02", actor: "E-Mail", message: "Manual order request created from customer email." },
      { id: "WF-10480-2", timestamp: "2026-05-14 15:20", actor: "Sales", message: "Design service item added to the draft order." },
      { id: "WF-10480-3", timestamp: "2026-05-15 08:40", actor: "System", message: "Customer reply required before artwork can be prepared." },
    ],
  },
  {
    id: "WF-10479",
    source: "woocommerce-weltflagge",
    externalId: "wc-58239",
    date: "2026-05-14",
    customer: "Hotel Sonnenblick",
    email: "info@hotel-sonnenblick.de",
    phone: "+49 711 909090",
    billingAddress: {
      company: "Hotel Sonnenblick",
      name: "Clara Hoffmann",
      street: "Panoramaweg 18",
      postalCode: "70173",
      city: "Stuttgart",
      country: "Germany",
    },
    shippingAddress: {
      company: "Hotel Sonnenblick",
      name: "Rezeption",
      street: "Panoramaweg 18",
      postalCode: "70173",
      city: "Stuttgart",
      country: "Germany",
    },
    items: [
      {
        name: "Roll-Up",
        sku: "RU-85-200",
        size: "85 x 200 cm",
        quantity: 3,
        printFile: { status: "approved", fileName: "WF-10479_rollup_85x200.pdf" },
        production: { status: "not_routed" },
      },
    ],
    amount: "69,90 EUR",
    paymentStatus: "Paid",
    artworkStatus: "Druckfreigabe erhalten",
    status: "Ready to ship",
    carrier: "UPS",
    trackingNumber: "",
    priority: "normal",
    deadline: "2026-05-16",
    notes: "Generate shipping label and attach tracking number.",
    timeline: [
      { id: "WF-10479-1", timestamp: "2026-05-14 10:10", actor: "WooCommerce", message: "Order imported from weltflagge.de." },
      { id: "WF-10479-2", timestamp: "2026-05-14 12:35", actor: "Production", message: "Roll-ups finished and moved to packing." },
      { id: "WF-10479-3", timestamp: "2026-05-15 09:15", actor: "Shipping", message: "Ready for UPS label generation." },
    ],
  },
  {
    id: "WF-10478",
    source: "ebay",
    externalId: "ebay-903118",
    date: "2026-05-13",
    customer: "Autohaus Klein GmbH",
    email: "marketing@autohaus-klein.de",
    phone: "+49 221 777888",
    billingAddress: {
      company: "Autohaus Klein GmbH",
      name: "Laura Klein",
      street: "Automeile 4",
      postalCode: "50667",
      city: "Koeln",
      country: "Germany",
    },
    shippingAddress: {
      company: "Autohaus Klein GmbH",
      name: "Marketing",
      street: "Automeile 4",
      postalCode: "50667",
      city: "Koeln",
      country: "Germany",
    },
    items: [
      {
        name: "Meshbanner",
        sku: "MB-300-150",
        size: "300 x 150 cm",
        quantity: 1,
        printFile: { status: "approved", fileName: "WF-10478_meshbanner_300x150.pdf" },
        production: { manufacturer: "opinion", batchId: "batch-2026-05-14-opinion", status: "produced" },
      },
    ],
    amount: "134,20 EUR",
    paymentStatus: "Paid",
    artworkStatus: "Druckfreigabe erhalten",
    status: "Shipped",
    carrier: "DPD",
    trackingNumber: "DPD-193847561",
    priority: "normal",
    deadline: "2026-05-15",
    notes: "Tracking was sent to the marketplace buyer.",
    timeline: [
      { id: "WF-10478-1", timestamp: "2026-05-13 14:22", actor: "eBay", message: "Marketplace order imported." },
      { id: "WF-10478-2", timestamp: "2026-05-14 09:00", actor: "Production", message: "Meshbanner produced and packed." },
      { id: "WF-10478-3", timestamp: "2026-05-14 16:45", actor: "Shipping", message: "Tracking number sent to eBay buyer." },
    ],
  },
];

export function getOrderById(id: string) {
  return mockOrders.find((order) => order.id === id);
}
