import type { Manufacturer, ManufacturerId, ProductionBatch, ProductionRow } from "@/src/types/production";

export const manufacturers: Manufacturer[] = [
  {
    id: "opinion",
    name: "Opinion",
    contact: "production@opinion.example",
    specialty: "Normal fabric flags, mesh fabric, banners",
    exportFormat: "Standard order table",
  },
  {
    id: "logo_pl",
    name: "Logo.pl",
    contact: "orders@logo-pl.example",
    specialty: "155g premium flags and indoor satin Zimmerfahnen",
    exportFormat: "Premium fabric order table",
  },
  {
    id: "mph_maciej",
    name: "MPH - Maciej",
    contact: "maciej@mph.example",
    specialty: "Beachflags",
    exportFormat: "Beachflag order table",
  },
];

export const manufacturerLabels: Record<ManufacturerId, string> = {
  opinion: "Opinion",
  logo_pl: "Logo.pl",
  mph_maciej: "MPH - Maciej",
  needs_review: "Needs review",
};

export const productionRows: ProductionRow[] = [
  {
    id: "prod-WF-10482-1",
    manufacturer: "opinion",
    orderId: "WF-10482",
    customer: "Stadtverwaltung Musterstadt",
    productName: "Hissfahne",
    sku: "HF-120-300",
    material: "Normal Stoff",
    size: "120 x 300 cm",
    quantity: 2,
    finishing: "Rings all around",
    printFile: { status: "received", fileName: "WF-10482_hissfahne_preview.pdf" },
    productionStatus: "draft",
    batchId: "batch-2026-05-16-opinion",
    deadline: "2026-05-20",
    notes: "Send after Druckfreigabe is received.",
    routingReason: "Normal flag fabric routes to Opinion.",
  },
  {
    id: "prod-WF-10481-1",
    manufacturer: "opinion",
    orderId: "WF-10481",
    customer: "BakerBuildings UG",
    productName: "PVC Banner",
    sku: "BN-500-100",
    material: "PVC banner",
    size: "500 x 100 cm",
    quantity: 1,
    finishing: "Hemmed and eyelets every 50 cm",
    printFile: { status: "approved", fileName: "WF-10481_banner_500x100.pdf" },
    productionStatus: "sent",
    batchId: "batch-2026-05-16-opinion",
    deadline: "2026-05-18",
    notes: "Production ready.",
    routingReason: "Banners route to Opinion.",
  },
  {
    id: "prod-WF-10480-1",
    manufacturer: "mph_maciej",
    orderId: "WF-10480",
    customer: "Feuerwehr Beispiel e.V.",
    productName: "Beachflag inkl. Gestaltungsservice",
    sku: "BF-M-DESIGN",
    material: "Beachflag fabric",
    size: "M",
    quantity: 1,
    finishing: "With tunnel seam for pole system",
    printFile: { status: "missing", fileName: "" },
    productionStatus: "not_routed",
    deadline: "2026-05-17",
    notes: "Customer reply needed before export.",
    routingReason: "Beachflags route to MPH - Maciej.",
  },
  {
    id: "prod-WF-10479-1",
    manufacturer: "needs_review",
    orderId: "WF-10479",
    customer: "Hotel Sonnenblick",
    productName: "Roll-Up",
    sku: "RU-85-200",
    material: "Roll-up display",
    size: "85 x 200 cm",
    quantity: 3,
    finishing: "System included",
    printFile: { status: "approved", fileName: "WF-10479_rollup_85x200.pdf" },
    productionStatus: "not_routed",
    deadline: "2026-05-16",
    notes: "No manufacturer rule exists for roll-ups yet.",
    routingReason: "Rule missing: roll-up products need manual assignment.",
  },
  {
    id: "prod-WF-10478-1",
    manufacturer: "opinion",
    orderId: "WF-10478",
    customer: "Autohaus Klein GmbH",
    productName: "Meshbanner",
    sku: "MB-300-150",
    material: "Mesh Stoff",
    size: "300 x 150 cm",
    quantity: 1,
    finishing: "Hemmed and eyelets",
    printFile: { status: "approved", fileName: "WF-10478_meshbanner_300x150.pdf" },
    productionStatus: "produced",
    batchId: "batch-2026-05-14-opinion",
    deadline: "2026-05-15",
    notes: "Already shipped in mock data, kept here as historical example.",
    routingReason: "Mesh fabric routes to Opinion.",
  },
  {
    id: "prod-demo-logo-1",
    manufacturer: "logo_pl",
    orderId: "WF-10477",
    customer: "Messebau Nord GmbH",
    productName: "Premium Hissfahne",
    sku: "HF-155-150-400",
    material: "Fahnenstoff 155 g - perMarin-N-Qualitaet",
    size: "150 x 400 cm",
    quantity: 4,
    finishing: "Left side with snap hooks",
    printFile: { status: "approved", fileName: "WF-10477_premium_hissfahne_155g.pdf" },
    productionStatus: "draft",
    batchId: "batch-2026-05-16-logo_pl",
    deadline: "2026-05-19",
    notes: "Premium fabric sample row for Logo.pl batch preview.",
    routingReason: "155g premium fabric routes to Logo.pl.",
  },
  {
    id: "prod-demo-logo-2",
    manufacturer: "logo_pl",
    orderId: "WF-10476",
    customer: "Praxis Lindenhof",
    productName: "Zimmerfahne Satin",
    sku: "ZF-SATIN-80-120",
    material: "Satin indoor fabric",
    size: "80 x 120 cm",
    quantity: 2,
    finishing: "Top sleeve, bottom hem",
    printFile: { status: "approved", fileName: "WF-10476_zimmerfahne_satin.pdf" },
    productionStatus: "draft",
    batchId: "batch-2026-05-16-logo_pl",
    deadline: "2026-05-21",
    notes: "Indoor satin sample row for Logo.pl routing.",
    routingReason: "Indoor satin Zimmerfahnen route to Logo.pl.",
  },
];

export function getRowsForManufacturer(manufacturer: ManufacturerId) {
  return productionRows.filter((row) => row.manufacturer === manufacturer);
}

export function getDraftBatches(): ProductionBatch[] {
  return manufacturers.map((manufacturer) => ({
    id: `batch-2026-05-16-${manufacturer.id}`,
    manufacturer: manufacturer.id,
    date: "2026-05-16",
    status: "Draft",
    rows: getRowsForManufacturer(manufacturer.id),
  }));
}
