ALTER TYPE "OrderSource" ADD VALUE IF NOT EXISTS 'ANGEBOT_PDF';

CREATE TYPE "OrderItemType" AS ENUM ('PRODUCTION_ITEM', 'ACCESSORY_ITEM', 'SERVICE_ITEM', 'SHIPPING_ITEM');

ALTER TABLE "OrderItem"
ADD COLUMN "itemType" "OrderItemType" NOT NULL DEFAULT 'PRODUCTION_ITEM';

